import type {Parameters,Site} from './physiology';
import {sites,metrics} from './physiology';
type Registry={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
export function registerLabTools(read:()=>Parameters,write:(p:Parameters)=>void,selection?:{read:()=>Site[];write:(sites:Site[])=>void}){
 const context=(document as unknown as {modelContext?:Registry}).modelContext;if(!context?.registerTool)return()=>{};
 const life=new AbortController();
 const definitions=[{name:'read_biosensing_experiment',description:'Read current virtual sensor parameters and synthetic propagation timings.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({parameters:read(),selected_sites:selection?.read()||[],timing:(selection?.read()||[]).map(site=>({site,...metrics({...read(),site})})),model:'synthetic-unvalidated'})},
 {name:'configure_biosensing_experiment',description:'Configure the visible synthetic experiment with heart rate, respiratory rate and PPG sensor site.',inputSchema:{type:'object',properties:{hr:{type:'number',minimum:40,maximum:180},rr:{type:'number',minimum:6,maximum:40},site:{type:'string',enum:Object.keys(sites)},selected_sites:{type:'array',items:{type:'string',enum:Object.keys(sites)},uniqueItems:true,maxItems:6}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{
 if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object');
 const patch=input as Record<string,unknown>;for(const [key,value]of Object.entries(patch)){if(!['hr','rr','site','selected_sites'].includes(key))throw new Error('Unsupported parameter');if(key==='selected_sites'&&(!Array.isArray(value)||value.some(s=>typeof s!=='string'||!Object.hasOwn(sites,s))||new Set(value).size!==value.length))throw new Error('Invalid selected sites');if(key==='site'&&(typeof value!=='string'||!Object.hasOwn(sites,value)))throw new Error('Invalid sensor site');if(key==='hr'&&(typeof value!=='number'||!Number.isFinite(value)||value<40||value>180))throw new Error('Heart rate must be 40–180');if(key==='rr'&&(typeof value!=='number'||!Number.isFinite(value)||value<6||value>40))throw new Error('Respiratory rate must be 6–40');}
 const {selected_sites,...parameters}=patch;const selected=selected_sites as Site[]|undefined;const next={...read(),...parameters}as Parameters;if(selected?.length&&!selected.includes(next.site))next.site=selected[0];write(next);if(selected)selection?.write(selected);else if(patch.site)selection?.write([...new Set([...(selection?.read()||[]),next.site])]);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));return{parameters:next,selected_sites:selection?.read()||[],timing:(selection?.read()||[]).map(site=>({site,...metrics({...next,site})}))};
 }}];
 for(const tool of definitions){try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{/* Optional browser API; the lab remains usable. */}}
 return()=>life.abort();
}
