'use client';
import {useEffect,useRef,useState} from 'react';
import {LabHeader} from '../../simulator-nav';
import {useLanguage} from '../../language';
import {useRenderQuality} from '../../render-quality-control';
import {ringSample,ringCsv,ringPressure} from '../../../lib/ring/model.js';
import type {RingScene} from '../../../lib/ring/scene';
import './ring.css';
type Sample=ReturnType<typeof ringSample>;
export default function RingLab(){
 const en=useLanguage()==='en',tx=(ko:string,english:string)=>en?english:ko;
 const host=useRef<HTMLDivElement>(null),scene=useRef<RingScene|null>(null),buffer=useRef<Sample[]>([]),time=useRef(0),physicalHeight=useRef(0);
 const [loaded,setLoaded]=useState(false),[error,setError]=useState(false),[running,setRunning]=useState(true),[contact,setContact]=useState(true),[motion,setMotion]=useState(false),[skin,setSkin]=useState(100),[hr,setHr]=useState(64),[rr,setRr]=useState(14),[spo2,setSpo2]=useState(97),[samples,setSamples]=useState<Sample[]>([]);
 const [heightCm,setHeight]=useState(0),[cycle,setCycle]=useState(false),[sbp,setSbp]=useState(120),[dbp,setDbp]=useState(80);
 const config=useRef({running,contact,motion,hr,rr,spo2,heightCm,cycle,sbp,dbp});config.current={running,contact,motion,hr,rr,spo2,heightCm,cycle,sbp,dbp};useRenderQuality(scene);
 useEffect(()=>{let active=true;import('../../../lib/ring/scene').then(({RingScene})=>{if(!active||!host.current)return;try{const s=new RingScene(host.current);scene.current=s;s.load().then(()=>{if(active){s.setContact(config.current.contact);s.moving=config.current.motion;setLoaded(true)}}).catch((e)=>{if(active)setError(true)})}catch{setError(true)}}).catch((e)=>{if(active)setError(true)});
 let ticks=0;const id=setInterval(()=>{const c=config.current;if(!c.running||document.hidden)return;time.current+=.02;const target=c.heightCm+(c.cycle?20*Math.sin(2*Math.PI*time.current/8):0),step=Math.max(-.3,Math.min(.3,target-physicalHeight.current));physicalHeight.current+=step;const sample=ringSample(time.current,{...c,cycle:false,heightCm:physicalHeight.current,heightVelocity:step*.5});buffer.current.push(sample);scene.current?.setHeight(sample.heightCm);if(scene.current)scene.current.moving=c.motion;if(buffer.current.length>600)buffer.current.shift();if(++ticks%5===0)setSamples([...buffer.current])},20);
 return()=>{active=false;clearInterval(id);scene.current?.dispose();scene.current=null};},[]);
 useEffect(()=>{if(scene.current)scene.current.moving=running&&motion},[running,motion]);
 const latest=samples.at(-1),valid=contact&&!motion&&Math.abs(latest?.velocity??0)<=.025;
 const height=latest?.heightCm??heightCm,bp=latest??ringPressure(heightCm,sbp,dbp);
 function exportCsv(){const url=URL.createObjectURL(new Blob([ringCsv(buffer.current)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='soma-ring-synthetic.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <main className="portal ring-page"><LabHeader active="ring"/><div className="portal-content"><div className="portal-heading"><div><span className="portal-kicker">03 / RING SLEEP SENSING</span><h1>{tx('링 수면 센싱','Ring Sleep Sensing')}</h1><p>{tx('손가락 광학 센서와 움직임으로 탐색하는 수면 모니터링','Explore sleep monitoring through finger optics and motion.')}</p></div><button className="ring-button" onClick={exportCsv} disabled={!samples.length}>{tx('CSV 내보내기','Export CSV')}</button></div>
 <p className="ring-note">{tx('공개용 합성 신호 데모 · 링 채널만으로 구성한 PSG 보조 컨셉입니다. EEG·EOG·턱 EMG가 포함된 완전한 PSG, 수면 단계 또는 AHI 판정은 제공하지 않습니다.','Synthetic public demo · A ring-channel adjunct concept, not full PSG. No EEG, EOG, chin EMG, sleep staging or AHI diagnosis.')}</p>
 <div className="ring-metrics">{[[tx('시뮬레이션 맥박','Simulated pulse'),valid?hr:'—','bpm'],['SpO₂',valid?spo2:'—','%'],[tx('신호 품질','Signal quality'),latest?.quality??0,'%'],[tx('신호 상태','Signal state'),!contact?tx('미착용','Off finger'):!valid?tx('움직임 잡음','Motion artifact'):tx('안정','Stable'),'']].map(([label,value,unit])=><article key={label}><span>{label}</span><strong>{value} <small>{unit}</small></strong></article>)}</div>
 <section className="ring-card ring-pressure"><div className="ring-card-head"><h2>{tx('손 높이에 따른 국소 혈압','Local pressure vs hand height')}</h2><button className="ring-button" aria-pressed={cycle} onClick={()=>{setCycle(!cycle);setHeight(0)}}>{tx('손 올리기·내리기 반복','Raise / lower hand')} {cycle?'ON':'OFF'}</button></div><div className="ring-metrics"><article><span>{tx('심장 높이 기준 입력','Heart-level input')}</span><strong>{sbp}/{dbp} <small>mmHg</small></strong></article><article><span>{tx('손가락 위치 혈압 · 모델','Finger pressure · model')}</span><strong>{bp.sbp.toFixed(0)}/{bp.dbp.toFixed(0)} <small>mmHg</small></strong></article><article><span>{tx('심장 대비 손 높이','Hand above heart')}</span><strong>{height.toFixed(1)} <small>cm</small></strong></article><article><span>ΔP = −ρgΔh</span><strong>{bp.offset.toFixed(1)} <small>mmHg</small></strong></article></div><div className="ring-controls ring-inputs"><label>{tx('손 높이','Hand height')}<input aria-label="Hand height" type="range" min="-30" max="30" value={heightCm} onChange={e=>{setHeight(+e.target.value);setCycle(false)}}/><output>{heightCm} cm</output></label><label>{tx('수축기 기준','Reference SBP')}<input type="range" min="100" max="160" value={sbp} onChange={e=>setSbp(+e.target.value)}/><output>{sbp} mmHg</output></label><label>{tx('이완기 기준','Reference DBP')}<input type="range" min="60" max="95" value={dbp} onChange={e=>setDbp(+e.target.value)}/><output>{dbp} mmHg</output></label></div><Trace samples={samples} fields={['sbp','dbp']} colors={['#efae82','#84c5ec']} labels={['Local SBP · mmHg','Local DBP · mmHg']} range={[0,210]}/><p className="ring-note">{tx('손을 올리면 국소 압력이 감소하고 내리면 증가합니다. 약 0.78 mmHg/cm. 심장 기준 혈압은 고정됩니다. 이는 정수압 모델이며 링 PPG로 혈압을 추정한 결과가 아닙니다. 움직임 중에는 광학 신호를 아티팩트로 표시합니다.','Raising the hand lowers local pressure; lowering it raises pressure (~0.78 mmHg/cm). Heart-level pressure stays fixed. This is a hydrostatic model, not BP estimated from ring PPG. Movement marks optical signals as artifacts.')} <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC11409525/" target="_blank" rel="noreferrer">AHA · {tx('자세와 혈압 측정','Position & BP measurement')}</a></p></section>
 <div className="ring-layout"><section className="ring-card"><div className="ring-card-head"><h2>{tx('손·손목 해부학과 검지 링','Hand anatomy · index-finger ring')}</h2><button className="ring-button" disabled={!loaded} onClick={()=>scene.current?.focus(true)}>{tx('링 확대','Focus ring')}</button><button className="ring-button" disabled={!loaded} onClick={()=>scene.current?.focus(false)}>{tx('전체 보기','Full hand')}</button></div><div className="ring-view" ref={host}><div className="ring-position-readout">{tx('심장 대비','Above heart')}: {height.toFixed(1)} cm · {bp.sbp.toFixed(0)}/{bp.dbp.toFixed(0)} mmHg</div>{!loaded&&<span className="ring-loading">{error?tx('모델 로딩 실패 · 새로고침해 주세요','Model unavailable · reload to retry'):tx('손 해부학 모델 로딩 중…','Loading anatomical hand…')}</span>}</div><div className="ring-controls"><label>{tx('손 높이','Hand height')}<input aria-label="3D hand height" type="range" min="-30" max="30" value={heightCm} onChange={e=>{setHeight(+e.target.value);setCycle(false)}}/><output>{heightCm} cm</output></label><label>{tx('피부 투명도','Skin opacity')} <input type="range" min="10" max="100" value={skin} onChange={e=>{setSkin(+e.target.value);scene.current?.setSkin(+e.target.value/100)}}/><output>{skin}%</output></label><button className="ring-button" aria-pressed={contact} onClick={()=>{setContact(!contact);scene.current?.setContact(!contact)}}>{tx('링 착용','Ring contact')} {contact?'ON':'OFF'}</button></div><p className="ring-note">{tx('기존 해부학 메시 사용 · 드래그 회전 / 휠 확대. 검지 근위부 피부에 맞춰 링 형상을 구성합니다.','Original anatomical mesh · Drag to orbit, scroll to zoom. Band geometry follows the proximal index-finger skin.')}</p></section>
 <section className="ring-card"><div className="ring-card-head"><h2>{tx('광학·움직임 채널','Optical & motion channels')}</h2><button className="ring-button" aria-pressed={running} onClick={()=>setRunning(!running)}>{running?tx('일시정지','Pause'):tx('재생','Resume')}</button></div><Trace samples={samples} fields={['red','ir']} colors={['#ff7c87','#ad9cff']} labels={['Red · 660 nm','IR · 940 nm']} range={!valid&&contact?[.4,1.6]:[.995,1.04]}/><Trace samples={samples} fields={['ax','ay','az']} colors={['#a4e4d0','#e5bd7d','#73b8e8']} labels={['ACC X','ACC Y','ACC Z']} range={[-.8,1.6]}/><p className="ring-note">{tx('PPG: 정규화 광량 · ACC: g · 최근 12초. 맥박·SpO₂는 아래 입력한 합성 기준값이며 검증된 추정 결과가 아닙니다.','PPG: normalized intensity · ACC: g · Last 12 s. Pulse and SpO₂ show synthetic input references, not validated estimates.')}</p><div className="ring-controls ring-inputs">{[[tx('맥박 입력','Pulse input'),hr,40,120,setHr,'bpm'],[tx('호흡 입력','Respiration input'),rr,6,30,setRr,'/min'],[tx('SpO₂ 입력','SpO₂ input'),spo2,80,100,setSpo2,'%']].map(([label,value,min,max,set,unit])=><label key={String(label)}>{String(label)}<input type="range" min={Number(min)} max={Number(max)} value={Number(value)} onChange={e=>(set as (v:number)=>void)(+e.target.value)}/><output>{Number(value)} {String(unit)}</output></label>)}<button className="ring-button" aria-pressed={motion} onClick={()=>{setMotion(!motion);if(scene.current)scene.current.moving=!motion}}>{tx('뒤척임 아티팩트','Turning artifact')} {motion?'ON':'OFF'}</button></div></section></div></div></main>
}
function Trace({samples,fields,colors,labels,range}:{samples:Sample[];fields:('red'|'ir'|'ax'|'ay'|'az'|'sbp'|'dbp')[];colors:string[];labels:string[];range:number[]}){const end=samples.at(-1)?.t??12,start=end-12;return <div className="ring-trace"><div className="ring-legend">{labels.map((s,i)=><span key={s} style={{color:colors[i]}}>{s}</span>)}</div><svg viewBox="0 0 600 150" role="img" aria-label={labels.join(', ')}>{[0,1,2,3,4].map(i=><g key={i}><line x1="40" x2="592" y1={16+i*27} y2={16+i*27} stroke="#2d3e47"/><text x="2" y={20+i*27} fill="#8da5ae" fontSize="10">{(range[1]-i*(range[1]-range[0])/4).toFixed(2)}</text></g>)}{fields.map((key,i)=><polyline key={key} fill="none" stroke={colors[i]} strokeWidth="1.6" points={samples.map(s=>`${40+(s.t-start)/12*552},${16+(range[1]-s[key])/(range[1]-range[0])*108}`).join(' ')}/>)}<text x="40" y="145" fill="#8da5ae" fontSize="10">−12 s</text><text x="567" y="145" fill="#8da5ae" fontSize="10">0 s</text></svg></div>}
